version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: laravel_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - laravel

  adminer:
    image: adminer
    container_name: laravel_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - laravel
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  laravel:
    driver: bridge